name: First workflow demo
on: workflow_dispatch

jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World"
      - name: print message
        run: echo "This is my first git hub action"
      - name: Combo execuite
        run: 
          echo "This is number 1"
          echo "This is number 2"
