name: Forth workflow demo
on: 
  # workflow_dispatch
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
  push:
    branches:
      - main
      - demo_branch
      - 'dev_*'
jobs:
  show_info:
    runs-on: ubuntu-latest
    steps:
      - name: Output 'github' Context
        run: echo "${{ toJSON( github ) }}"
