name: third workflow demo
on: workflow_dispatch
jobs:
  code-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: download code
        uses: actions/checkout@v4
  nginx-deploy-test:
    needs: [code-checkout]
    runs-on: ubuntu-latest
    steps:
      - name: donwload container
        run: |
          docker image pull nginx
          docker image ls
          docker container run -d -p 8080:80 nginx
      - name: Test Web Deployment
        run: |
          python3 -c "import requests; r=requests.get('http://localhost:8080'); print(r.status_code)"
          curl -s localhost:8080
        